// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: examples/account.proto

public final class AccountOuterClass {
  private AccountOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code EyeColor}
   */
  public enum EyeColor
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNSPECIFIED = 0;</code>
     */
    UNSPECIFIED(0),
    /**
     * <code>GEEN = 1;</code>
     */
    GEEN(1),
    /**
     * <code>BLUE = 2;</code>
     */
    BLUE(2),
    /**
     * <code>BROWN = 3;</code>
     */
    BROWN(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNSPECIFIED = 0;</code>
     */
    public static final int UNSPECIFIED_VALUE = 0;
    /**
     * <code>GEEN = 1;</code>
     */
    public static final int GEEN_VALUE = 1;
    /**
     * <code>BLUE = 2;</code>
     */
    public static final int BLUE_VALUE = 2;
    /**
     * <code>BROWN = 3;</code>
     */
    public static final int BROWN_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EyeColor valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EyeColor forNumber(int value) {
      switch (value) {
        case 0: return UNSPECIFIED;
        case 1: return GEEN;
        case 2: return BLUE;
        case 3: return BROWN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EyeColor>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EyeColor> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EyeColor>() {
            public EyeColor findValueByNumber(int number) {
              return EyeColor.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return AccountOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final EyeColor[] VALUES = values();

    public static EyeColor valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EyeColor(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:EyeColor)
  }

  public interface AccountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Account)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>bytes thumbnail = 3;</code>
     * @return The thumbnail.
     */
    com.google.protobuf.ByteString getThumbnail();

    /**
     * <code>bool is_active = 4;</code>
     * @return The isActive.
     */
    boolean getIsActive();

    /**
     * <code>float height = 5;</code>
     * @return The height.
     */
    float getHeight();

    /**
     * <code>repeated string phones = 6;</code>
     * @return A list containing the phones.
     */
    java.util.List<java.lang.String>
        getPhonesList();
    /**
     * <code>repeated string phones = 6;</code>
     * @return The count of phones.
     */
    int getPhonesCount();
    /**
     * <code>repeated string phones = 6;</code>
     * @param index The index of the element to return.
     * @return The phones at the given index.
     */
    java.lang.String getPhones(int index);
    /**
     * <code>repeated string phones = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the phones at the given index.
     */
    com.google.protobuf.ByteString
        getPhonesBytes(int index);

    /**
     * <code>.EyeColor eye_color = 7;</code>
     * @return The enum numeric value on the wire for eyeColor.
     */
    int getEyeColorValue();
    /**
     * <code>.EyeColor eye_color = 7;</code>
     * @return The eyeColor.
     */
    AccountOuterClass.EyeColor getEyeColor();
  }
  /**
   * Protobuf type {@code Account}
   */
  public static final class Account extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Account)
      AccountOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Account.newBuilder() to construct.
    private Account(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Account() {
      name_ = "";
      thumbnail_ = com.google.protobuf.ByteString.EMPTY;
      phones_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      eyeColor_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Account();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Account(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readUInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {

              thumbnail_ = input.readBytes();
              break;
            }
            case 32: {

              isActive_ = input.readBool();
              break;
            }
            case 45: {

              height_ = input.readFloat();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                phones_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              phones_.add(s);
              break;
            }
            case 56: {
              int rawValue = input.readEnum();

              eyeColor_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          phones_ = phones_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AccountOuterClass.internal_static_Account_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AccountOuterClass.internal_static_Account_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AccountOuterClass.Account.class, AccountOuterClass.Account.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>uint32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int THUMBNAIL_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString thumbnail_;
    /**
     * <code>bytes thumbnail = 3;</code>
     * @return The thumbnail.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getThumbnail() {
      return thumbnail_;
    }

    public static final int IS_ACTIVE_FIELD_NUMBER = 4;
    private boolean isActive_;
    /**
     * <code>bool is_active = 4;</code>
     * @return The isActive.
     */
    @java.lang.Override
    public boolean getIsActive() {
      return isActive_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 5;
    private float height_;
    /**
     * <code>float height = 5;</code>
     * @return The height.
     */
    @java.lang.Override
    public float getHeight() {
      return height_;
    }

    public static final int PHONES_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList phones_;
    /**
     * <code>repeated string phones = 6;</code>
     * @return A list containing the phones.
     */
    public com.google.protobuf.ProtocolStringList
        getPhonesList() {
      return phones_;
    }
    /**
     * <code>repeated string phones = 6;</code>
     * @return The count of phones.
     */
    public int getPhonesCount() {
      return phones_.size();
    }
    /**
     * <code>repeated string phones = 6;</code>
     * @param index The index of the element to return.
     * @return The phones at the given index.
     */
    public java.lang.String getPhones(int index) {
      return phones_.get(index);
    }
    /**
     * <code>repeated string phones = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the phones at the given index.
     */
    public com.google.protobuf.ByteString
        getPhonesBytes(int index) {
      return phones_.getByteString(index);
    }

    public static final int EYE_COLOR_FIELD_NUMBER = 7;
    private int eyeColor_;
    /**
     * <code>.EyeColor eye_color = 7;</code>
     * @return The enum numeric value on the wire for eyeColor.
     */
    @java.lang.Override public int getEyeColorValue() {
      return eyeColor_;
    }
    /**
     * <code>.EyeColor eye_color = 7;</code>
     * @return The eyeColor.
     */
    @java.lang.Override public AccountOuterClass.EyeColor getEyeColor() {
      @SuppressWarnings("deprecation")
      AccountOuterClass.EyeColor result = AccountOuterClass.EyeColor.valueOf(eyeColor_);
      return result == null ? AccountOuterClass.EyeColor.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeUInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!thumbnail_.isEmpty()) {
        output.writeBytes(3, thumbnail_);
      }
      if (isActive_ != false) {
        output.writeBool(4, isActive_);
      }
      if (java.lang.Float.floatToRawIntBits(height_) != 0) {
        output.writeFloat(5, height_);
      }
      for (int i = 0; i < phones_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, phones_.getRaw(i));
      }
      if (eyeColor_ != AccountOuterClass.EyeColor.UNSPECIFIED.getNumber()) {
        output.writeEnum(7, eyeColor_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!thumbnail_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, thumbnail_);
      }
      if (isActive_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isActive_);
      }
      if (java.lang.Float.floatToRawIntBits(height_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, height_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < phones_.size(); i++) {
          dataSize += computeStringSizeNoTag(phones_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getPhonesList().size();
      }
      if (eyeColor_ != AccountOuterClass.EyeColor.UNSPECIFIED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, eyeColor_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AccountOuterClass.Account)) {
        return super.equals(obj);
      }
      AccountOuterClass.Account other = (AccountOuterClass.Account) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getThumbnail()
          .equals(other.getThumbnail())) return false;
      if (getIsActive()
          != other.getIsActive()) return false;
      if (java.lang.Float.floatToIntBits(getHeight())
          != java.lang.Float.floatToIntBits(
              other.getHeight())) return false;
      if (!getPhonesList()
          .equals(other.getPhonesList())) return false;
      if (eyeColor_ != other.eyeColor_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + THUMBNAIL_FIELD_NUMBER;
      hash = (53 * hash) + getThumbnail().hashCode();
      hash = (37 * hash) + IS_ACTIVE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsActive());
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getHeight());
      if (getPhonesCount() > 0) {
        hash = (37 * hash) + PHONES_FIELD_NUMBER;
        hash = (53 * hash) + getPhonesList().hashCode();
      }
      hash = (37 * hash) + EYE_COLOR_FIELD_NUMBER;
      hash = (53 * hash) + eyeColor_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AccountOuterClass.Account parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AccountOuterClass.Account parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AccountOuterClass.Account parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AccountOuterClass.Account parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AccountOuterClass.Account parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AccountOuterClass.Account parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AccountOuterClass.Account parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AccountOuterClass.Account parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AccountOuterClass.Account parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AccountOuterClass.Account parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AccountOuterClass.Account parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AccountOuterClass.Account parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AccountOuterClass.Account prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Account}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Account)
        AccountOuterClass.AccountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AccountOuterClass.internal_static_Account_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AccountOuterClass.internal_static_Account_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AccountOuterClass.Account.class, AccountOuterClass.Account.Builder.class);
      }

      // Construct using AccountOuterClass.Account.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        thumbnail_ = com.google.protobuf.ByteString.EMPTY;

        isActive_ = false;

        height_ = 0F;

        phones_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        eyeColor_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AccountOuterClass.internal_static_Account_descriptor;
      }

      @java.lang.Override
      public AccountOuterClass.Account getDefaultInstanceForType() {
        return AccountOuterClass.Account.getDefaultInstance();
      }

      @java.lang.Override
      public AccountOuterClass.Account build() {
        AccountOuterClass.Account result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public AccountOuterClass.Account buildPartial() {
        AccountOuterClass.Account result = new AccountOuterClass.Account(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.name_ = name_;
        result.thumbnail_ = thumbnail_;
        result.isActive_ = isActive_;
        result.height_ = height_;
        if (((bitField0_ & 0x00000001) != 0)) {
          phones_ = phones_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.phones_ = phones_;
        result.eyeColor_ = eyeColor_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AccountOuterClass.Account) {
          return mergeFrom((AccountOuterClass.Account)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AccountOuterClass.Account other) {
        if (other == AccountOuterClass.Account.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getThumbnail() != com.google.protobuf.ByteString.EMPTY) {
          setThumbnail(other.getThumbnail());
        }
        if (other.getIsActive() != false) {
          setIsActive(other.getIsActive());
        }
        if (other.getHeight() != 0F) {
          setHeight(other.getHeight());
        }
        if (!other.phones_.isEmpty()) {
          if (phones_.isEmpty()) {
            phones_ = other.phones_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePhonesIsMutable();
            phones_.addAll(other.phones_);
          }
          onChanged();
        }
        if (other.eyeColor_ != 0) {
          setEyeColorValue(other.getEyeColorValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AccountOuterClass.Account parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AccountOuterClass.Account) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>uint32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>uint32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString thumbnail_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes thumbnail = 3;</code>
       * @return The thumbnail.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getThumbnail() {
        return thumbnail_;
      }
      /**
       * <code>bytes thumbnail = 3;</code>
       * @param value The thumbnail to set.
       * @return This builder for chaining.
       */
      public Builder setThumbnail(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        thumbnail_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes thumbnail = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearThumbnail() {
        
        thumbnail_ = getDefaultInstance().getThumbnail();
        onChanged();
        return this;
      }

      private boolean isActive_ ;
      /**
       * <code>bool is_active = 4;</code>
       * @return The isActive.
       */
      @java.lang.Override
      public boolean getIsActive() {
        return isActive_;
      }
      /**
       * <code>bool is_active = 4;</code>
       * @param value The isActive to set.
       * @return This builder for chaining.
       */
      public Builder setIsActive(boolean value) {
        
        isActive_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_active = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsActive() {
        
        isActive_ = false;
        onChanged();
        return this;
      }

      private float height_ ;
      /**
       * <code>float height = 5;</code>
       * @return The height.
       */
      @java.lang.Override
      public float getHeight() {
        return height_;
      }
      /**
       * <code>float height = 5;</code>
       * @param value The height to set.
       * @return This builder for chaining.
       */
      public Builder setHeight(float value) {
        
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float height = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeight() {
        
        height_ = 0F;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList phones_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePhonesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          phones_ = new com.google.protobuf.LazyStringArrayList(phones_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string phones = 6;</code>
       * @return A list containing the phones.
       */
      public com.google.protobuf.ProtocolStringList
          getPhonesList() {
        return phones_.getUnmodifiableView();
      }
      /**
       * <code>repeated string phones = 6;</code>
       * @return The count of phones.
       */
      public int getPhonesCount() {
        return phones_.size();
      }
      /**
       * <code>repeated string phones = 6;</code>
       * @param index The index of the element to return.
       * @return The phones at the given index.
       */
      public java.lang.String getPhones(int index) {
        return phones_.get(index);
      }
      /**
       * <code>repeated string phones = 6;</code>
       * @param index The index of the value to return.
       * @return The bytes of the phones at the given index.
       */
      public com.google.protobuf.ByteString
          getPhonesBytes(int index) {
        return phones_.getByteString(index);
      }
      /**
       * <code>repeated string phones = 6;</code>
       * @param index The index to set the value at.
       * @param value The phones to set.
       * @return This builder for chaining.
       */
      public Builder setPhones(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePhonesIsMutable();
        phones_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string phones = 6;</code>
       * @param value The phones to add.
       * @return This builder for chaining.
       */
      public Builder addPhones(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePhonesIsMutable();
        phones_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string phones = 6;</code>
       * @param values The phones to add.
       * @return This builder for chaining.
       */
      public Builder addAllPhones(
          java.lang.Iterable<java.lang.String> values) {
        ensurePhonesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, phones_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string phones = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearPhones() {
        phones_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string phones = 6;</code>
       * @param value The bytes of the phones to add.
       * @return This builder for chaining.
       */
      public Builder addPhonesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensurePhonesIsMutable();
        phones_.add(value);
        onChanged();
        return this;
      }

      private int eyeColor_ = 0;
      /**
       * <code>.EyeColor eye_color = 7;</code>
       * @return The enum numeric value on the wire for eyeColor.
       */
      @java.lang.Override public int getEyeColorValue() {
        return eyeColor_;
      }
      /**
       * <code>.EyeColor eye_color = 7;</code>
       * @param value The enum numeric value on the wire for eyeColor to set.
       * @return This builder for chaining.
       */
      public Builder setEyeColorValue(int value) {
        
        eyeColor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.EyeColor eye_color = 7;</code>
       * @return The eyeColor.
       */
      @java.lang.Override
      public AccountOuterClass.EyeColor getEyeColor() {
        @SuppressWarnings("deprecation")
        AccountOuterClass.EyeColor result = AccountOuterClass.EyeColor.valueOf(eyeColor_);
        return result == null ? AccountOuterClass.EyeColor.UNRECOGNIZED : result;
      }
      /**
       * <code>.EyeColor eye_color = 7;</code>
       * @param value The eyeColor to set.
       * @return This builder for chaining.
       */
      public Builder setEyeColor(AccountOuterClass.EyeColor value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        eyeColor_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.EyeColor eye_color = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearEyeColor() {
        
        eyeColor_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Account)
    }

    // @@protoc_insertion_point(class_scope:Account)
    private static final AccountOuterClass.Account DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AccountOuterClass.Account();
    }

    public static AccountOuterClass.Account getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Account>
        PARSER = new com.google.protobuf.AbstractParser<Account>() {
      @java.lang.Override
      public Account parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Account(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Account> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Account> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public AccountOuterClass.Account getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Account_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Account_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026examples/account.proto\"\207\001\n\007Account\022\n\n\002" +
      "id\030\001 \001(\r\022\014\n\004name\030\002 \001(\t\022\021\n\tthumbnail\030\003 \001(" +
      "\014\022\021\n\tis_active\030\004 \001(\010\022\016\n\006height\030\005 \001(\002\022\016\n\006" +
      "phones\030\006 \003(\t\022\034\n\teye_color\030\007 \001(\0162\t.EyeCol" +
      "or*:\n\010EyeColor\022\017\n\013UNSPECIFIED\020\000\022\010\n\004GEEN\020" +
      "\001\022\010\n\004BLUE\020\002\022\t\n\005BROWN\020\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Account_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Account_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Account_descriptor,
        new java.lang.String[] { "Id", "Name", "Thumbnail", "IsActive", "Height", "Phones", "EyeColor", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
