# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: examples/account.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x65xamples/account.proto\"\x87\x01\n\x07\x41\x63\x63ount\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tthumbnail\x18\x03 \x01(\x0c\x12\x11\n\tis_active\x18\x04 \x01(\x08\x12\x0e\n\x06height\x18\x05 \x01(\x02\x12\x0e\n\x06phones\x18\x06 \x03(\t\x12\x1c\n\teye_color\x18\x07 \x01(\x0e\x32\t.EyeColor*:\n\x08\x45yeColor\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x08\n\x04GEEN\x10\x01\x12\x08\n\x04\x42LUE\x10\x02\x12\t\n\x05\x42ROWN\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'examples.account_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EYECOLOR._serialized_start=164
  _EYECOLOR._serialized_end=222
  _ACCOUNT._serialized_start=27
  _ACCOUNT._serialized_end=162
# @@protoc_insertion_point(module_scope)
